spring.application.name=auth-service

# Database Configuration
spring.datasource.url=jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/bookstore
spring.datasource.username=${PG_USER:postgres}
spring.datasource.password=${PG_PASSWORD:password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
# 1 hour
token.expiration=3600000
token.secret.key=cf5d2af9e67df53719a3b84fda2e2248015dbc2e01bf867b66325020088fac36